server:
  port: 8080

template:
  templateList:
    - {"templateId":"1","templateFilePath":"/home/yangxin/IdeaProjects/kafka-study/src/main/resources/template/template.json","active": true}
    - {"templateId":"2","templateFilePath":"/home/yangxin/IdeaProjects/kafka-study/src/main/resources/template/template.json","active": false}
  template-result-type: 0  # 0-文件获取 1-数据库获取 2-ES
  template-result-file-path: "/home/yangxin/IdeaProjects/kafka-study/src/main/resources/template/templateResult.json"
